<?php
/** @var \App\View $this */
/** @var \App\Domain\Data\Component $CNF */
/** @var \App\Domain\Data\Component $ITS */
/** @var \App\Domain\Data\Component $SM */
/** @var \App\Domain\Data\Component $CDS */
/** @var \App\Domain\Data\Component $PROC */
/** @var \App\Domain\Data\Component $RM */
/** @var \App\Domain\Data\Component $TERM */
/** @var \App\Domain\Data\Component $QUERY */
/** @var \App\Domain\Data\Component $AM */
/** @var \App\Domain\Data\Component $LANG */
/** @var \App\Domain\Data\Component $BASE */
/** @var string $title */
/** @var string $page */

use App\Domain\Data\Status;

switch ($page) {
    case 'release_baseline':
        $statuses = [
            'Retired' => '',
            'Development' => '',
        ];
        break;
    case 'development_baseline':
        $statuses = [
            'Retired' => '',
            'Development' => 'checked',
        ];
        break;
}

?>
<h1 class="text-center">
    <?= $title ?>
</h1>

<div class="text-right mt-5 px-2"><h5>
    <?php foreach ($statuses as $statusText => $checked) {
        $status = Status::from($statusText);
    ?>
    <span class="align-top badge badge-light mx-1 px-1 border">
        <label for="toggle-<?= $status->name ?>" class="form-check-label align-middle mr-1">
            <span class="badge align-text-bottom badge-<?= $status->getBadge() ?>"><?= $status->getShort() ?></span> - <?= $status->value ?>
        </label>
        <input type="checkbox" class="align-middle" <?= $checked ?> id="toggle-<?= $status->name ?>" data-toggle="toggle" data-size="xs">
    </span>
    <?php } ?>
</h5></div>

<div class="d-flex flex-column">

    <div class="specs_category_box <?= $CNF->status->getCssClass($page) ?>">
        <h5>Conformance</h5>
        <div id="cnf_group" class="group_box">
            <?= $this->fetch('block/component_row.phtml', $CNF) ?>
        </div>
    </div>

    <div class="specs_category_box">
        <h5>Implementation Technologies</h5>
        <div id="its_group" class="group_box">
            <?= $this->fetch('block/component_row.phtml', $ITS) ?>
        </div>
    </div>

    <div class="specs_category_box">
        <h4 class="text-center">Abstract Specifications</h4>
        <p class="text-center">Technology-independent primary specifications for the openEHR health computing platform</p>

        <h5 class="<?= $SM->status->getCssClass($page) ?>">Platform Service Interface</h5>
        <div id="services_group" class="group_box <?= $SM->status->getCssClass($page) ?>">
            <?= $this->fetch('block/component_row.phtml', $SM) ?>
        </div>
        <h5>Process and CDS</h5>
        <div id="analytics_group" class="group_box">
            <?= $this->fetch('block/component_row.phtml', $CDS) ?>
            <?= $this->fetch('block/component_row.phtml', $PROC) ?>
        </div>
        <h5>Content</h5>
        <div id="content_group" class="group_box">
            <?= $this->fetch('block/component_row.phtml', $RM) ?>
            <?= $this->fetch('block/component_row.phtml', $TERM) ?>
        </div>
        <h5>Formalisms</h5>
        <div id="formalisms_group" class="group_box">
            <?= $this->fetch('block/component_row.phtml', $QUERY) ?>
            <?= $this->fetch('block/component_row.phtml', $AM) ?>
            <?= $this->fetch('block/component_row.phtml', $LANG) ?>
        </div>
        <h5>Foundations</h5>
        <div id="foundations_group" class="group_box">
            <?= $this->fetch('block/component_row.phtml', $BASE) ?>
        </div>
    </div>

</div>

<?= $this->fetch('block/status_legend.phtml') ?>
