<?php
/** @var string $title */
/** @var string $id */
/** @var \App\Domain\Data\Release $release */
/** @var \App\Domain\Data\Release[] $releases */
/** @var \App\Domain\Data\Jira $jira */
/** @var \App\Domain\Data\Specification[] $specifications */
/** @var \App\Domain\Data\Expression[] $expressions */
/** @var \App\Domain\Data\Note $note */
/** @var \App\Domain\Data\Package[] $packages */
/** @var \App\Domain\Data\Type $type */
/** @var \App\Domain\Data\Component $component */

use App\Domain\Data\Release;
use App\Helper\File;

$hasSpecificationsWithNotes = false;
foreach ($specifications as $spec) {
    if ($spec->notes) {
        $hasSpecificationsWithNotes = true;
        break;
    }
}

$hasReleasedReleases = false;
foreach ($releases as $rel) {
    if ($rel->isReleased()) {
        $hasReleasedReleases = true;
        break;
    }
}
$latestRelease = $component->getReleaseById(Release::LATEST);

$diagramFile = new File($component->getAssetFilename('openehr_block_diagram.svg'));
if ($diagramFile->isValid()) {
    $diagramLink = $release->getLink() . '/openehr_block_diagram.svg';
} else {
    $diagramLink = $release->getLinkOfDevelopment() . '/openehr_block_diagram.svg';
}
?>
<img src="<?= $diagramLink ?>" alt="openEHR components" class="openehr-block-diagram mx-auto d-block img-fluid mt-5">

<h1 class="text-center">
    <?= $title ?>
</h1>

<nav class="nav justify-content-center">
    <?php if ($release->isDevelopment()) { ?>
    <span class="mx-1"><a href="<?= $jira->getOpenIssues() ?>" target="_blank">Open Issues</a></span> |
    <span class="mx-1"><a href="<?= $jira->getRoadmap() ?>" target="_blank">Roadmap</a></span> |
    <span class="mx-1"><a href="<?= $jira->getHistory() ?>" target="_blank">History</a></span>
    <?php } else {?>
    <span class="mx-1"><a href="<?= $release->jira->getIssues() ?>" target="_blank">Issues Fixed</a></span> |
    <span class="mx-1"><a href="<?= $release->jira->getChanges() ?>" target="_blank">Changes Implemented</a></span> |
    <span class="mx-1"><a href="<?= $jira->getRoadmap() ?>" target="_blank">Roadmap</a></span> |
    <span class="mx-1"><a href="<?= $jira->getHistory() ?>" target="_blank">History</a></span>
    <?php } ?>
</nav>

<h2 id="_specifications">Specifications</h2>
<table class="table table-sm">
    <thead class="thead-light">
        <tr>
            <th class="w-long">Specification</th>
            <th>Description</th>
            <?php if ($hasSpecificationsWithNotes) { ?>
            <th class="w-short">Notes</th>
            <?php } ?>
        </tr>
    </thead>
    <tbody class="border-bottom">
    <?php foreach ($specifications as $spec) {
        if (!$spec->hasExplicitLink()) {
            $file = new File($spec->getFilename());
            if (!$file->isValid()) {
                continue;
            }
        }
        ?>
        <tr>
            <td>
                <span class="badge badge-<?= $spec->spec_status->getBadge() ?> spec-status" title="Specification status is <?= $spec->spec_status->name ?>, copyright <?= $spec->copyright_year ?>-<?= date('Y') ?>."><?= $spec->spec_status->name ?></span>
                <a href="<?= $spec->getLink() ?>" title="<?= $spec->description ?>" target="_blank"><?= $spec->title_short ?></a>
            </td>
            <td><?= $spec->summary ?></td>
            <?php if ($hasSpecificationsWithNotes) { ?>
            <td>
                <?php foreach ($spec->notes as $note) { ?>
                <a href="<?= $note->link ?>" target="_blank"><?= $note->text ?></a><br/>
                <?php } ?>
            </td>
            <?php } ?>
        </tr>
    <?php } ?>
    </tbody>
</table>

<?php if ($hasReleasedReleases) { ?>
<h2 id="_releases">Releases</h2>
<table class="table table-sm">
    <thead class="thead-light">
        <tr>
            <th class="w-short">Release</th>
            <th class="w-short">Date</th>
            <th>Description</th>
        </tr>
    </thead>
    <tbody class="border-bottom">
    <?php
    foreach ($releases as $rel) {
        if ($rel->isReleased()) {
            if ($rel->is($latestRelease->getId())) { ?>
        <tr>
            <td class="font-weight-bold"><a href="<?= $rel->getLink() ?>">Release <?= $rel->id ?></a></td>
            <td><?= $rel->date->format('d-M-Y') ?></td>
            <td id="_latest">
                The latest released specifications of <?= $component->title ?> (<?= $id ?>) Component |
                <a href="<?= $rel->jira->getChanges() ?>" target="_blank">Release notes</a>
            </td>
        </tr>
            <?php } else { ?>
        <tr>
            <td><a href="<?= $rel->getLink() ?>">Release <?= $rel->id ?></a></td>
            <td><?= $rel->date->format('d-M-Y') ?></td>
            <td><a href="<?= $rel->jira->getChanges() ?>" target="_blank">Release notes</a></td>
        </tr>
            <?php } ?>
        <?php } ?>
    <?php } ?>
    </tbody>
</table>
<?php } ?>

<h2 id="_development">Work In Progress</h2>
<table class="table table-sm">
    <thead class="thead-light">
        <tr>
            <th class="w-long">Release</th>
            <th>Description</th>
        </tr>
    </thead>
    <tbody class="border-bottom">
        <tr>
            <td><a href="<?= $release->getLinkOfDevelopment() ?>">Development</a></td>
            <td>
                The development version of specifications of <?= $component->title ?> (<?= $id ?>) Component |
                <a href="https://github.com/openEHR/specifications-<?=$id?>" target="_blank">GitHub repo</a>
            </td>
        </tr>
    <?php foreach ($releases as $release) {
        if (!$release->isReleased()) { ?>
        <tr>
            <td><a>Release <?= $release->id ?></a></td>
            <td>
                <a href="<?= $release->jira->getIssues() ?>" target="_blank">Issues</a> |
                <a href="<?= $release->jira->getChanges() ?>" target="_blank">Changes</a>
            </td>
        </tr>
        <?php } ?>
    <?php } ?>
    </tbody>
</table>

<h2 id="_computable_expressions">Computable Expressions</h2>
<table class="table table-sm">
    <thead class="thead-light">
        <tr>
            <th class="w-long">Resource</th>
            <th>Description</th>
        </tr>
    </thead>
    <tbody class="border-bottom">
    <?php foreach ($expressions as $expr) {
        ?>
        <tr>
            <td><a href="<?= $expr->getLink() ?>" title="<?= $expr->title ?>" target="_blank"><?= $expr->id ?></a></td>
            <td><?= $expr->description ?></td>
        </tr>
    <?php } ?>
    </tbody>
</table>

<?php if ($packages) { ?>
<h2 id="_class_index">Class Index</h2>
<table class="table table-sm">
    <thead class="thead-light">
        <tr>
            <th class="w-long">Packages</th>
            <th>Classes</th>
        </tr>
    </thead>
    <tbody class="border-bottom">
    <?php foreach ($packages as $package) { ?>
        <tr id="_package_<?= $package->name ?>">
            <td><?= $package->name ?></td>
            <td>
            <?php foreach ($package->types as $type) { ?>
                <span class="badge badge-light"><a id="<?= $type->fragment ?>" href="<?= $type->getLink() ?>" target="_blank"><?= $type->name ?></a></span>
            <?php } ?>
            </td>
        </tr>
    <?php } ?>
    </tbody>
</table>
<?php } ?>
