<?php
/** @var \App\Domain\Data\Component $component */
/** @var \App\Helper\ITSAsset $dir */
/** @var string $title */

?>
<h1 class="text-center">
    <?= $title ?>
</h1>
<p>
    The followings are part of the <a href="<?=$component->release->getLink()?>"><?= $component->title ?></a>
    specifications under <a href="<?=$dir->getLink()?>"><?=$dir->getName()?></a> section:
</p>
<ul>
<?php foreach ($dir->getContents() as $item) { ?>
    <li><a href="<?=$item->getLink()?>"><?=$item->getBasename()?></a></li>
<?php } ?>
</ul>
