<?php
/** @var string $title */
/** @var \App\Domain\Data\Release[] $releases */
?>
<h1 class="text-center">
    <?=$title?>
</h1>
<p>
    The following table shows releases of all openEHR specification components.
    Note that RM and BASE Release 1.0.2 are conversions of the original 'Release 1.0.2' specifications,
    available on the <a href="/historical_releases">Historical Releases</a> page.
</p>
<table class="table table-sm">
    <thead class="thead-light">
    <tr>
        <th class="w-long">Release</th>
        <th class="w-short">Date</th>
        <th>Description</th>
    </tr>
    </thead>
    <tbody class="border-bottom">
    <?php foreach ($releases as $release) {
    ?>
    <tr>
        <td><a href="<?= $release->getLink() ?>" target="_blank"><?= $release->component->id ?> Release <?= $release->id ?></a></td>
        <td><?= $release->date->format('d-M-Y') ?></td>
        <td><a href="<?= $release->jira->getChanges() ?>" target="_blank">Release notes</a></td>
    </tr>
    <?php } ?>
    </tbody>
</table>
