<?php
/** @var \App\Domain\Data\Component $CNF */
/** @var \App\Domain\Data\Component $ITS */
/** @var \App\Domain\Data\Component $SM */
/** @var \App\Domain\Data\Component $CDS */
/** @var \App\Domain\Data\Component $PROC */
/** @var \App\Domain\Data\Component $RM */
/** @var \App\Domain\Data\Component $TERM */
/** @var \App\Domain\Data\Component $QUERY */
/** @var \App\Domain\Data\Component $AM */
/** @var \App\Domain\Data\Component $LANG */
/** @var \App\Domain\Data\Component $BASE */

$architecture_overview = $BASE->getSpecificationById('architecture_overview');
$archetype_technology = $AM->getSpecificationById('Overview');

?>

<div class="d-flex flex-column">

    <div class="specs_category_box d-grid" id="global_box">
        <h5>Start Here</h5>
        <div class="row no-gutters specs_cell">
            <div class="col specs_item">
                <h6><a href="<?= $architecture_overview->getLink() ?>" target="_blank"><?= $architecture_overview->title_short ?></a><br></h6>
                <?= $architecture_overview->micro_summary ?>
            </div>
            <div class="col specs_item">
                <h6><a href="<?= $archetype_technology->getLink() ?>" target="_blank"><?= $archetype_technology->title_short ?></a><br></h6>
                <?= $archetype_technology->micro_summary ?>
            </div>
            <div class="col specs_item">
                <h6><a href="/Services+Landscape+for+e-Health" target="_blank">Services Landscape</a><br></h6>
                Map of e-health services at enterprise, community and region levels
            </div>
            <div class="col specs_item">
                <h6><a href="/releases/UML/latest/index.html">GLOBAL UML</a><br></h6>
                Generated global UML website
            </div>
            <div class="col specs_item">
                <h6><a href="/classes">CLASS INDEX</a><br></h6>
                Global openEHR class link list
            </div>
        </div>
    </div>

    <img src="/openehr_block_diagram.svg" alt="openEHR components" class="openehr-block-diagram mx-auto d-block img-fluid mt-4">

    <div class="specs_category_box">
        <h5>Conformance</h5>
        <div id="cnf_group" class="group_box">
            <?= $this->fetch('block/component_row.phtml', $CNF) ?>
        </div>
    </div>

    <div class="specs_category_box">
        <h5>Implementation Technologies</h5>
        <div id="its_group" class="group_box">
            <?= $this->fetch('block/component_row.phtml', $ITS) ?>
        </div>
    </div>

    <div class="specs_category_box">
        <h4 class="text-center">Abstract Specifications</h4>
        <p class="text-center">Technology-independent primary specifications for the openEHR health computing platform</p>

        <h5>Platform Service Interface</h5>
        <div id="services_group" class="group_box">
            <?= $this->fetch('block/component_row.phtml', $SM) ?>
        </div>
        <h5>Process and CDS</h5>
        <div id="analytics_group" class="group_box">
            <?= $this->fetch('block/component_row.phtml', $CDS) ?>
            <?= $this->fetch('block/component_row.phtml', $PROC) ?>
        </div>
        <h5>Content</h5>
        <div id="content_group" class="group_box">
            <?= $this->fetch('block/component_row.phtml', $RM) ?>
            <?= $this->fetch('block/component_row.phtml', $TERM) ?>
        </div>
        <h5>Formalisms</h5>
        <div id="formalisms_group" class="group_box">
            <?= $this->fetch('block/component_row.phtml', $QUERY) ?>
            <?= $this->fetch('block/component_row.phtml', $AM) ?>
            <?= $this->fetch('block/component_row.phtml', $LANG) ?>
        </div>
        <h5>Foundations</h5>
        <div id="foundations_group" class="group_box">
            <?= $this->fetch('block/component_row.phtml', $BASE) ?>
        </div>
    </div>

</div>
