x-web-environment: &web
  networks:
    - caddy
    - monitor
  depends_on:
    - caddy
  env_file:
    - path: ./.env
      required: false
  restart: unless-stopped
x-monitor-environment: &monitor
  networks:
    - monitor
  profiles:
    - monitor
  restart: unless-stopped

services:
  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - caddy-data:/data
      - caddy-config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./public:/app/public:ro
    networks:
      - caddy
      - monitor
    restart: unless-stopped

  web:
    <<: *web
    build:
      target: production
    volumes:
      - web-repos:/data/repos
      - web-releases:/data/releases

  web-dev:
    <<: *web
    build:
      target: development
    profiles:
      - dev
    volumes:
      - ./:/app
      - ./repos:/data/repos
      - ./releases:/data/releases
      - composer-cache:/data/.cache/composer

  prometheus:
    <<: *monitor
    image: prom/prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
  cadvisor:
    <<: *monitor
    image: gcr.io/cadvisor/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
  node-exporter:
    <<: *monitor
    image: prom/node-exporter
  php-fpm-exporter:
    <<: *monitor
    image: hipages/php-fpm_exporter:latest
    environment:
      PHP_FPM_SCRAPE_URI: "tcp://web:9000/status,tcp://web-dev:9000/status"
      PHP_FPM_LOG_LEVEL: "debug"

volumes:
  caddy-data:
  caddy-config:
  composer-cache:
  web-repos:
  web-releases:

networks:
  caddy:
  monitor:
