x-global-environment: &global
  networks:
    - caddy
  restart: unless-stopped

services:
  caddy:
    <<: *global
    image: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy-data:/data/
      - ./Caddyfile:/etc/caddy/Caddyfile

  web:
    <<: *global
    build:
      dockerfile: web.Dockerfile
    volumes:
      - web-repos:/data/repos
      - web-releases:/data/releases
    depends_on:
      - caddy

  web-dev:
    <<: *global
    build:
      dockerfile: web.Dockerfile
    profiles:
      - dev
    volumes:
      - .:/data/website
      - web-repos:/data/repos
      - web-releases:/data/releases
    depends_on:
      - caddy


volumes:
  caddy-data:
  web-repos:
  web-releases:

networks:
  caddy: