global:
  scrape_interval: 10s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - prometheus:9090
  - job_name: node
    static_configs:
      - targets:
        - node-exporter:9100
  - job_name: cadvisor
    static_configs:
      - targets:
        - cadvisor:8080
  - job_name: apache
    static_configs:
      - targets:
        - apache-exporter:9117
