<?php
/** @var string $id */
/** @var string $title */
/** @var string $page */
/** @var \App\Domain\Data\Release $release */
/** @var \App\Domain\Data\Release[] $releases */
/** @var \App\Domain\Data\Jira $jira */
/** @var \App\Domain\Data\Specification[] $specifications */
/** @var \App\Domain\Data\Expression[] $expressions */
/** @var \App\Domain\Data\Type $type */

$spec_blacklist = [
    'architecture_overview',
    'iso_18308_conformance_statement',
    'archetype_profile',
]
?>
<div id="<?= $id ?>" class="d-flex component_row">
    <div class="flex-shrink-0 component_cell">
        <h6>
            <a href="<?= $release->getLink() ?>" target="_blank"><?= $id ?></a>
        </h6>
        <small>(<?= $title ?>)</small>
        <p>
            <a href="<?= $jira->getOpenIssues() ?>" target="_blank">PRs</a> |
            <a href="<?= $jira->getCrs() ?>" target="_blank">CRs</a>
        </p>
        <p>
        <?php foreach ($release->getExpressions() as $expr) {
            if ($expr->isOwned() && $expr->isUML()) {
            ?>
            <a href="<?= $expr->getLink() ?>" target="_blank" title="<?= $expr->description ?>"><?= $expr->title ?></a><br/>
            <?php }
        } ?>
        </p>
    </div>
    <div class="flex-grow-1 d-grid specs_cell">
        <div class="row no-gutters">
        <?php foreach ($release->getSpecifications() as $spec) {
            if (!in_array($spec->id, $spec_blacklist)) { ?>
            <div class="col specs_item" title="<?= $spec->summary ?>">
                <h6>
                    <a href="<?= $spec->getLink() ?>" target="_blank"><?= $spec->title_short ?></a>
                    <span class="align-top badge badge-<?= $spec->getStatusBadge() ?> spec-status-short mr-1" title="Specification status is <?= $spec->getStatusTitle() ?>."><?= $spec->getStatusShort() ?></span>
                </h6>
                <?php if ($spec->micro_summary) { ?>
                    <?= $spec->micro_summary ?><br/>
                <?php } ?>
                <?php foreach ($spec->summary_types as $type) { ?>
                    <span class="badge badge-light text-truncate"><a href="<?= $type->getLink() ?>" target="_blank"><?= $type->name ?></a></span>
                <?php } ?>
            </div><?php }
        } ?>
        </div>
    </div>
    <div class="d-none d-md-block flex-shrink-0 releases">
        <?php if ($page === 'release_baseline') { ?>
            <?php foreach ($releases as $rel) {
                if (!$rel->isReleased()) {
                    continue;
                }
                $cssClass = $rel->is($release->id) ? 'font-weight-bold' : '';
                ?>
                    <a href="<?= $rel->getLink() ?>" class="<?= $cssClass ?>" target="_blank"><?= $rel->id ?></a>
                    (<?= $rel->date->format('d-M-Y')?>)<br/>
            <?php } ?>
        <?php } else { ?>
            <a href="<?= $release->getLink() ?>" target="_blank"><?= App\Domain\Data\Release::DEVELOPMENT ?></a><br/>
            <?php foreach ($releases as $rel) {
                if ($rel->isReleased()) { ?>
                    <a href="<?= $rel->getLink() ?>" target="_blank"><?= $rel->id ?></a>
                    (<?= $rel->date->format('d-M-Y')?>)<br/>
                <?php } else { ?>
                    <a href="<?= $rel->jira->getChanges() ?>" target="_blank"><?= $rel->id ?></a>
                    (in progress)<br/>
                <?php } ?>
            <?php } ?>
        <?php } ?>
    </div>
</div>
