<?php
/** @var string $spec_status */
/** @var string $copyright_year */


switch ($spec_status) {
    case 'STABLE':
        $badge = 'badge-success';
        $spec_status_short = $spec_status;
        break;
    case 'TRIAL':
        $badge = 'badge-primary';
        $spec_status_short = $spec_status;
        break;
    case 'DEV':
    case 'DEVELOPMENT':
        $badge = 'badge-secondary';
        $spec_status_short = 'DEV';
        break;
    case 'SUPERSEDED':
        $badge = 'badge-warning';
        $spec_status_short = $spec_status;
        break;
    case 'OBSOLETE':
    case 'ARCHIVED':
        $badge = 'badge-danger';
        $spec_status_short = $spec_status;
        break;
    default:
        $badge = 'badge-light';
        $spec_status_short = $spec_status;
}
?>
<span class="badge <?= $badge ?>" title="Specification status is <?= $spec_status ?>, copyright <?= $copyright_year ?>."><?= $spec_status_short ?></span>
