<?php

use App\Domain\Data\Status;

?>
<div class="text-right">
    <h5><a href="https://www.openehr.org/change-process" target="_blank">Legend:</a>
        <span class="align-top badge badge-light mx-1 p-1 border">
            <span class="align-top badge badge-<?= Status::DEVELOPMENT->getBadge(); ?>"><?= Status::DEVELOPMENT->getShort() ?></span> - <?= Status::DEVELOPMENT->value ?>
        </span>
        <span class="align-top badge badge-light mx-1 p-1 border">
            <span class="align-top badge badge-<?= Status::TRIAL->getBadge(); ?>"><?= Status::TRIAL->getShort() ?></span> - <?= Status::TRIAL->value ?>
        </span>
        <span class="align-top badge badge-light mx-1 p-1 border">
            <span class="align-top badge badge-<?= Status::STABLE->getBadge(); ?>"><?= Status::STABLE->getShort() ?></span> - <?= Status::STABLE->value ?>
        </span>
        <span class="align-top badge badge-light mx-1 p-1 border">
            <span class="align-top badge badge-<?= Status::RETIRED->getBadge(); ?>"><?= Status::RETIRED->getShort() ?></span> - <?= Status::RETIRED->value ?>
        </span>
    </h5>
</div>
