<?php
    $statuses = \App\Domain\Data\Specification::STATUSES;
?>
<div class="text-right">
    <h5><a href="https://www.openehr.org/programs/specification/changeprocess" target="_blank">Legend:</a>
        <span class="align-top badge badge-light mx-1 p-1 border">
            <span class="align-top badge badge-<?= $statuses['DEV']['badge'] ?>"><?= $statuses['DEV']['short'] ?></span> - Development
        </span>
        <span class="align-top badge badge-light mx-1 p-1 border">
            <span class="align-top badge badge-<?= $statuses['TRIAL']['badge'] ?>"><?= $statuses['TRIAL']['short'] ?></span> - Trial
        </span>
        <span class="align-top badge badge-light mx-1 p-1 border">
            <span class="align-top badge badge-<?= $statuses['STABLE']['badge'] ?>"><?= $statuses['STABLE']['short'] ?></span> - Stable
        </span>
        <span class="align-top badge badge-light mx-1 p-1 border">
            <span class="align-top badge badge-<?= $statuses['RETIRED']['badge'] ?>"><?= $statuses['RETIRED']['short'] ?></span> - Retired
        </span>
    </h5>
</div>
