<?php 
/** @var \App\Domain\Data\Release $release */
/** @var \App\Domain\Data\Jira $jira */
/** @var \App\Domain\Data\Specification $spec */
/** @var \App\Domain\Data\Expression $expr */
/** @var \App\Domain\Data\Type $type */

$spec_blacklist = [
    'architecture_overview',
    'iso_18308_conformance_statement',
    'archetype_profile',
]
?>
<div id="<?= $id ?>" class="component_row">
    <div class="component_cell">
        <p class="component_name">
            <a href="<?= $release->getLink() ?>" target="_blank"><?= $id ?></a>
        </p>
        <p>(<?= $title ?>)</p>
        <p>
            <a href="<?= $jira->getOpenIssues() ?>" target="_blank">PRs</a> |
            <a href="<?= $jira->getCrs() ?>" target="_blank">CRs</a>
        </p>
        <p>
        <?php foreach ($expressions as $expr) {
            if ($expr->isOwned() && $expr->isUML()) {
            ?>
            <a href="<?= $expr->getLink() ?>" target="_blank" title="<?= $expr->description ?>"><?= $expr->title ?></a><br/>
            <?php }
        } ?>
        </p>
    </div>
    <div class="specs_cell">
        <?php foreach ($specifications as $spec) {
            if (!in_array($spec->id, $spec_blacklist)) { ?>
            <p class="specs_item" title="<?= $spec->summary ?>">
                <a href="<?= $spec->getLink() ?>" target="_blank"><?= $spec->title_short ?></a><br/>
                <?php if ($spec->micro_summary) { ?>
                    <?= $spec->micro_summary ?><br/>
                <?php } ?>
                <?php while ($type = current($spec->summary_types)) { ?>
                    <a href="<?=$type->getLink()?>" target="_blank"><?= $type->name ?></a><?php
                        if (next($spec->summary_types)) {
                            ?>, <?php
                        } ?>
                <?php } ?>
            </p><?php }
        } ?>
    </div>
    <p class="releases">
        <?php foreach ($releases as $release) {
        ?>
            <a href="<?= $release->isReleased() ? $release->getLink() : $release->jira->getChanges() ?>" target="_blank"><?= $release->id ?></a>
            (<?= $release->isReleased() ? $release->date->format('d-M-Y') : 'cooking' ?>)<br/>
        <?php } ?>
    </p>
</div>
