<?php
/** @var \App\Domain\Data\Release $release */
/** @var \App\Domain\Data\Jira $jira */
/** @var \App\Domain\Data\Specification $spec */
/** @var \App\Domain\Data\Expression $expr */
/** @var \App\Domain\Data\Note $note */
/** @var \App\Domain\Data\Package $package */
/** @var \App\Domain\Data\Type $type */

$hasSpecificationsWithNotes = false;
foreach ($specifications as $spec) {
    if ($spec->notes) {
        $hasSpecificationsWithNotes = true;
        break;
    }
}

?>
<img src="<?= $release->getLink() ?>/openehr_block_diagram.svg" alt="openEHR components" width="60%">
<h1>
    <?= $title ?> (<?= $id ?>) Component - <?= $release->id ?>
</h1>
<div class="title-para">
    <a href="<?= $release->jira->prs ?>" target="_blank"><?= $release->isLatest() ? 'Open Issues' : 'Issues Fixed' ?></a> |
    <a href="<?= $release->jira->crs ?>" target="_blank"><?= $release->isLatest() ? 'Roadmap' : 'Changes Implemented' ?></a>
</div>
<div>
    <h2><a name="_specifications"></a>Specifications</h2>
    <table>
        <thead>
        <tr>
            <th>Specification</th>
            <th>Description</th>
            <?php if ($hasSpecificationsWithNotes) { ?>
            <th>Notes</th>
            <?php } ?>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($specifications as $spec) {
            ?>
            <tr>
                <td><a href="<?= $spec->getLink() ?>" title="<?= $spec->description ?>" target="_blank"><?= $spec->title_short ?></a></td>
                <td><?= $spec->summary ?></td>
                <?php if ($hasSpecificationsWithNotes) { ?>
                <td>
                    <?php foreach ($spec->notes as $note) { ?>
                    <a href="<?= $note->link ?>" target="_blank"><?= $note->text ?></a><br/>
                    <?php } ?>
                </td>
                <?php } ?>
            </tr>
        <?php } ?>
        </tbody>
    </table>
</div>
<div>
    <h2><a name="_releases"></a>Releases</h2>
    <table>
        <thead>
        <tr>
            <th>Release</th>
            <th>Date</th>
            <th>Description</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($releases as $release) {
            if (!$release->isReleased()) { ?>
            <tr>
                <td><a>Release <?= $release->id ?></a></td>
                <td>cooking</td>
                <td><a href="<?= $release->jira->crs ?>" target="_blank">Release notes</a></td>
            </tr>
            <?php } else {?>
            <tr>
                <td><a href="<?= $release->getLink() ?>" target="_blank">Release <?= $release->id ?></a></td>
                <td><?= $release->date->format('d-M-Y') ?></td>
                <td><a href="<?= $release->jira->crs ?>" target="_blank">Release notes</a></td>
            </tr>
            <?php } ?>
        <?php } ?>
        </tbody>
    </table>
</div>
<div>
    <h2><a name="_computable_expressions"></a>Computable Expressions</h2>
    <table>
        <thead>
        <tr>
            <th>Resource</th>
            <th>Description</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($expressions as $expr) {
            ?>
            <tr>
                <td><a href="<?= $expr->getLink() ?>" title="<?= $expr->title ?>" target="_blank"><?= $expr->id ?></a></td>
                <td><?= $expr->description ?></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
</div>
<?php if ($packages) { ?>
<div>
    <h2><a name="_class_index"></a>Class Index</h2>
    <table>
        <thead>
        <tr>
            <th>Packages</th>
            <th>Classes</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($packages as $package) { ?>
            <tr>
                <td><a name="_package_<?= $package->name ?>"></a><?= $package->name ?></td>
                <td>
                    <ul>
                        <?php foreach ($package->types as $type) { ?>
                            <li><a name="<?= $type->fragment ?>"/><a href="<?= $type->getLink() ?>" target="_blank"><?= $type->name ?></a></li>
                        <?php } ?>
                    </ul>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
</div>
 <?php } ?>
