<img src="openehr_block_diagram.svg" alt="openEHR components" width="60%">
<h1 id="_reference_model_rm_component_latest" class="sect0">
    <a class="anchor" href="#_reference_model_rm_component_latest"></a>
    <?= $title ?> (<?= $id ?>) Component - <?= $release->id ?>
</h1>
<div class="openblock partintro title-para">
    <div class="content">
        <a href="https://specifications.openehr.org/components/RM/open_issues" target="_blank" rel="noopener">Open Issues</a> |
        <a href="https://specifications.openehr.org/components/RM/roadmap" target="_blank" rel="noopener">Roadmap</a> |
        <a href="https://specifications.openehr.org/components/RM/history" target="_blank" rel="noopener">Previous Releases</a>
    </div>
</div>
<div class="sect1">
    <h2 id="_specifications"><a class="anchor" href="#_specifications"></a>Specifications</h2>
    <div class="sectionbody">
        <table class="tableblock frame-all grid-all stretch">
            <colgroup>
                <col style="width: 16.6666%;">
                <col style="width: 83.3334%;">
            </colgroup>
            <thead>
            <tr>
                <th class="tableblock halign-left valign-top">Specification</th>
                <th class="tableblock halign-left valign-top">Description</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td class="tableblock halign-left valign-top"><p class="tableblock"><a href="/releases/RM/latest/ehr.html">EHR IM</a></p></td>
                <td class="tableblock halign-left valign-top"><p class="tableblock">The information model of the openEHR EHR.</p></td>
            </tr>
            <tr>
                <td class="tableblock halign-left valign-top"><p class="tableblock"><a href="/releases/RM/latest/demographic.html">Demographic IM</a></p></td>
                <td class="tableblock halign-left valign-top"><p class="tableblock">The openEHR demographics information model.</p></td>
            </tr>
            <tr>
                <td class="tableblock halign-left valign-top"><p class="tableblock"><a href="/releases/RM/latest/common.html">Common IM</a></p></td>
                <td class="tableblock halign-left valign-top"><p class="tableblock">Information model containing common concepts, including the archetype-enabling <code>LOCATABLE</code> class, party references, audits and attestations, change control, and authored resources.</p></td>
            </tr>
            <tr>
                <td class="tableblock halign-left valign-top"><p class="tableblock"><a href="/releases/RM/latest/data_structures.html">Data Structures IM</a></p></td>
                <td class="tableblock halign-left valign-top"><p class="tableblock">Information model of data structures, incuding a powerful model of time-series data.</p></td>
            </tr>
            <tr>
                <td class="tableblock halign-left valign-top"><p class="tableblock"><a href="/releases/RM/latest/data_types.html">Data Types IM</a></p></td>
                <td class="tableblock halign-left valign-top"><p class="tableblock">Information model of data types, including quantities, date/times, plain and coded text, time specification, multimedia and URIs.</p></td>
            </tr>
            <tr>
                <td class="tableblock halign-left valign-top"><p class="tableblock"><a href="/releases/RM/latest/support.html">Support IM</a></p></td>
                <td class="tableblock halign-left valign-top"><p class="tableblock">Support model defining identifiers, assumed types, and terminology interface specification used in the rest of the IMs.</p></td>
            </tr>
            <tr>
                <td class="tableblock halign-left valign-top"><p class="tableblock"><a href="/releases/RM/latest/integration.html">Integration IM</a></p></td>
                <td class="tableblock halign-left valign-top"><p class="tableblock">Information model for representing legacy data is a free-form Entry type for implementing integration solutions.</p></td>
            </tr>
            <tr>
                <td class="tableblock halign-left valign-top"><p class="tableblock"><a href="/releases/RM/latest/ehr_extract.html">EHR Extract IM</a></p></td>
                <td class="tableblock halign-left valign-top"><p class="tableblock">The information model of the EHR Extract, which is a serilialisation of content from an EHR.</p></td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
<div class="sect1">
    <h2 id="_computable_expressions"><a class="anchor" href="#_computable_expressions"></a>Computable Expressions</h2>
    <div class="sectionbody">
        <table class="tableblock frame-all grid-all stretch">
            <colgroup>
                <col style="width: 28.5714%;">
                <col style="width: 71.4286%;">
            </colgroup>
            <thead>
            <tr>
                <th class="tableblock halign-left valign-top">Resource</th>
                <th class="tableblock halign-left valign-top">Description</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td class="tableblock halign-left valign-top"><p class="tableblock"><a href="/releases/RM/latest/UML/openEHR_UML-RM.mdzip">openEHR_UML-RM.mdzip</a></p></td>
                <td class="tableblock halign-left valign-top"><p class="tableblock">UML file for MagicDraw 19 for RM model. Contains UML 2.5 standard XMI file.</p></td>
            </tr>
            <tr>
                <td class="tableblock halign-left valign-top"><p class="tableblock"><a href="/releases/BASE/latest/UML/openEHR_UML-Base.mdzip">openEHR_UML-Base.mdzip</a></p></td>
                <td class="tableblock halign-left valign-top"><p class="tableblock">UML file for MagicDraw 19 for BASE model (included by RM). Contains UML 2.5 standard XMI file.</p></td>
            </tr>
            </tbody>
        </table>
    </div>
</div>