<?php 
/** @var \App\Domain\Data\Release $release */
/** @var \App\Domain\Data\Jira $jira */
/** @var \App\Domain\Data\Specification $spec */
/** @var \App\Domain\Data\Expression $expr */
?>
<div id="<?= $id ?>" class="component_row">
    <div class="component_cell">
        <p class="component_name">
            <a href="<?= $release->getLink() ?>" target="_blank"><?= $id ?></a>
        </p>
        <p>(<?= $title ?>)</p>
        <p>
            <a href="<?= $jira->prs ?>" target="_blank">PRs</a> |
            <a href="<?= $jira->crs ?>" target="_blank">CRs</a>
        </p>
        <p>
        <?php foreach ($expressions as $expr) {
            if ($expr->isOwned()) {
            ?>
            <a href="<?= $expr->getLink() ?>" target="_blank" title="<?= $expr->description ?>"><?= $expr->title ?></a><br/>
            <?php }
        } ?>
        </p>
    </div>
    <div class="specs_cell">
        <?php foreach ($specifications as $spec) {
            ?>
            <p class="specs_item" title="<?= $spec->title ?> - <?= $spec->description ?>">
                <a href="<?= $spec->getLink() ?>" target="_blank"><?= $spec->title_short ?></a><br/>
                <?= $spec->keywords ?>
            </p>
        <?php } ?>
    </div>
    <p class="releases">
        <?php foreach ($releases as $release) {
        ?>
            <a href="<?= $release->isReleased() ? $release->getLink() : $release->jira->crs ?>" target="_blank"><?= $release->id ?></a>
            (<?= $release->isReleased() ? $release->date->format('d-M-Y') : 'cooking' ?>)<br/>
        <?php } ?>
    </p>
</div>
