<?php
/** @var \App\Domain\Data\Release $release */
/** @var \App\Domain\Data\Jira $jira */
/** @var \App\Domain\Data\Specification $spec */
/** @var \App\Domain\Data\Expression $expr */
?>
<img src="<?= $release->getLink() ?>/openehr_block_diagram.svg" alt="openEHR components" width="60%">
<h1>
    <?= $title ?> (<?= $id ?>) Component - <?= $release->id ?>
</h1>
<div class="title-para">
    <a href="<?= $release->jira->prs ?>" target="_blank"><?= $release->isLatest() ? 'Open Issues' : 'Issues Fixed' ?></a> |
    <a href="<?= $release->jira->crs ?>" target="_blank"><?= $release->isLatest() ? 'Roadmap' : 'Changes Implemented' ?></a>
</div>
<div>
    <h2><a href="#_specifications"></a>Specifications</h2>
    <table>
        <thead>
        <tr>
            <th>Specification</th>
            <th>Description</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($specifications as $spec) {
        ?>
        <tr>
            <td><a href="<?= $spec->getLink() ?>" title="<?= $spec->title ?>" target="_blank"><?= $spec->title_short ?></a></td>
            <td><?= $spec->description ?></td>
        </tr>
        <?php } ?>
        </tbody>
    </table>
</div>
<div>
    <h2><a href="#_computable_expressions"></a>Computable Expressions</h2>
    <table>
        <thead>
        <tr>
            <th>Resource</th>
            <th>Description</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($expressions as $expr) {
            ?>
            <tr>
                <td><a href="<?= $expr->getLink() ?>" title="<?= $expr->title ?>" target="_blank"><?= $expr->id ?></a></td>
                <td><?= $expr->description ?></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
</div>
