<h1><?= $title; ?></h1>
<p>
    The following releases were of all openEHR specifications, prior to components being created.
    All releases are now published as part of a component, and can be seen <a href="/latest_releases">here</a>.
</p>
<table class="TableBasic">
    <thead>
    <tr>
        <th>Release</th>
        <th>Date</th>
        <th>Description</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td><a href="/releases/1.0.2">Release 1.0.2</a></td>
        <td>31 December 2008</td>
        <td>22 Change Requests.<br/>
            <a href="https://openehr.atlassian.net/projects/SPEC/versions/10030" target="_blank">Release notes.</a>
        </td>
    </tr>
    <tr>
        <td><a href="/releases/1.0.1">Release 1.0.1</a></td>
        <td>15 April 2007</td>
        <td>56 Change Requests.<br/>
            <a href="https://openehr.atlassian.net/projects/SPEC/versions/10019" target="_blank">Release notes.</a>
        </td>
    </tr>
    <tr>
        <td><a href="/releases/1.0">Release 1.0</a></td>
        <td>07 February 2006</td>
        <td>54 Change Requests.<br/>
            <a href="https://openehr.atlassian.net/projects/SPEC/versions/10018" target="_blank">Release notes.</a>
        </td>
    </tr>
    <tr>
        <td>Release 0.96</td>
        <td>01 August 2005</td>
        <td>Error correction release.<br/>
            12 Change Requests <br/>
            <a href="https://openehr.atlassian.net/projects/SPEC/versions/10017" target="_blank">Release notes.</a>
        </td>
    </tr>
    <tr>
        <td><a href="/releases/0.95">Release 0.95</a></td>
        <td>15 March 2005</td>
        <td>Basic modelling changes.<br/>
            17 Change Requests.<br/>
            <a href="https://openehr.atlassian.net/projects/SPEC/versions/10016" target="_blank">Release notes.</a>
        </td>
    </tr>
    <tr>
        <td><a href="/releases/0.9">Release 0.9</a></td>
        <td>04 May 2004</td>
        <td>First complete release of openEHR.<br/>
            84 Change Requests<br/>
            <a href="https://openehr.atlassian.net/projects/SPEC/versions/10015" target="_blank">Release notes.</a>
        </td>
    </tr>
    </tbody>
</table>
