<!DOCTYPE HTML>

<html lang="en">

<head>
	
	<title>openEHR - <?=$title?></title>
	<meta charset="utf-8">	
	<meta name="description" content="openEHR provides open source specifications and reference implementations of future proof EHR systems">
	<meta name="keywords" content="archetypes, openEHR, EHR, electronic health record, electronic medical record, ADL, reference model, clinical models, healthcare, health informatics, medical informatics, EHR standards, ISO 18308, CEN 13606, health care software, open source software, knowledge modelling, patient-centric">
	<meta name="author" content="openEHR Foundation">
	<meta name="designer" content="Adriana Danilakova">
	<meta name="rating" content="General">
	<meta name="robots" content="All">
	<meta name="revisit-after" content="5 days">

	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<link rel="stylesheet" href="/styles/basic.css"  type="text/css">
	<link rel="stylesheet" href="/styles/pages.css"  type="text/css"> 
	
	<link rel="shortcut icon" href="/favicon.ico">
    <link rel="icon" sizes="16x16 32x32" href="/favicon.ico">

    <link rel="home" href="/">

	<meta name="google-site-verification" content="zfPZfHQ-5oXYT119aAi7HdZELv8ubHPCxvIFANVPzcU" />

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	
	<script src="/functions/menu_dropdown.js"></script> 
	<script src="/functions/paragraph_dropdown.js"></script>
	

	
</head>

<body>

<div id="MainFrame">
	
	<div id="TopPanelContainer">
	
		<div id="TopPanel">
			
			<div id="Logo">

				<a href="/"></a>
				
			</div>
				
			<div id="Motto">
			
				Open industry specifications, models and software for e-health
			
			</div>
			
			<div id="Utilities">
				
				<a href="https://www.openehr.org">openEHR Home</a> | <a href="/wiki" target="_blank">Wiki</a> | <a href="https://openehr.atlassian.net/secure/BrowseProjects.jspa?selectedCategory=all&selectedProjectType=all" target="_blank">Jira</a> | <a href="https://www.openehr.org/ckm">CKM</a>
				
				<div id="Search">
			
					<script>
					  (function() {
						var cx = '013258992131926468583:q3vo4hyneyu';
						var gcse = document.createElement('script');
						gcse.type = 'text/javascript';
						gcse.async = true;
						gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
						var s = document.getElementsByTagName('script')[0];
						s.parentNode.insertBefore(gcse, s);
					  })();
					</script>
					<gcse:search></gcse:search>

				</div>
			
			</div>
			
		</div>
	
	</div>
	
	<div id = "TopMenuContainer">
	
		<div id="TopMenu">

		</div> 
		
	</div>

	<div id = "MainAreaContainer">
	
	<div id="MainArea">
		
		<div id="SideMenu">
            <ul>
                <li><a href="/latest_releases" <?php if($page === 'latest_releases'){?> class="active"<?php }?>>Latest Releases</a></li>
                <li><a href="/historical_releases" <?php if($page === 'historical_releases'){?> class="active"<?php }?>>Historical Releases</a></li>
                <br/>
                <li><a href="https://openehr.atlassian.net/secure/Dashboard.jspa?selectPageId=10190" target="_blank">Issue Trackers</a></li>
                <li><a href="https://www.openehr.org/programs/specification/governance" target="_blank">Governance</a></li>
                <br/>
                <li><a href="https://www.openehr.org/governance/intellectual_property" target="_blank">IP and Licensing</a></li>
                <li><a href="https://discourse.openehr.org/c/specifications" target="_blank">Discourse Forum</a></li>
                <li><a href="/wiki/display/spec/Specifications+Home" target="_blank">Wiki</a></li>
            </ul>
		</div>
        <div id="Content">
            <?=$content?>
        </div>


    </div>
        <br class="clear">
    </div>

    <div id = "BottomMenuContainer">

        <div id="BottomMenu">
            <div class="BottomMenuPart floatLeft">
                <div class="BottomMenuSection floatRight">
                    <p class="MenuHeading">Community <sup style="font-size:8px; font-style:italic;">Follow Us</sup></p>
                    <ul>
                        <li><a href="/wiki" target="_blank">Wiki</a></li>
                        <li><a href="https://github.com/openEHR" target="_blank">GitHub</a></li>
                        <li><a href="https://www.youtube.com/openEHR" target="_blank">YouTube</a></li>
                    </ul>
                </div>
            </div>

            <br class="clear">
        </div>

    </div>



    <div id = "BottomPanelContainer">

        <div id="BottomPanel">
            <div id = "WebLinks">
                <span><a href ="https://www.openehr.org/using_the_site/terms_of_use">Terms of use</a> | <a href ="https://www.openehr.org/using_the_site/privacy_policy">Privacy policy</a> | <a href ="https://www.openehr.org/using_the_site/feedback">Feedback</a> | <a href ="/using_the_site/site_map">Site map</a> | <a href="mailto:webmaster@openehr.org">Webmaster</a></span><br/>
                <span>Copyright &copy; <?php echo date("Y");?> openEHR Foundation. All rights reserved</span>
            </div>

            <div id = "Acknowledgements">
                <span>Acknowledgements: <a href="https://www.atlassian.com/" target="_blank">Atlassian</a> (Jira, Confluence) | <a href="https://www.nomagic.com/" target="_blank">NoMagic</a> (MagicDraw UML) | <a href="http://asciidoctor.org/" target="_blank">AsciiDoctor</a> (publishing) | <a href="https://github.com/" target="_blank">GitHub</a> (DVCS) | <a href="https://en.wikipedia.org/wiki/LAMP_%28software_bundle%29" target="_blank">LAMP</a> dev community</span>
            </div>

            <br class="clear">
        </div>

    </div>

</div>

<script type="text/javascript">
    var dropdown=new MENU.dropdown.init("dropdown", {id:'menu', active:'menuhover'});
</script>

</body>

</html>
