    <div id = "BottomMenuContainer">
        <div id="BottomMenu">
            <div class="BottomMenuPart floatLeft">
                <div class="BottomMenuSection floatRight">
                    <p class="MenuHeading">Community <sup style="font-size:8px; font-style:italic;">Follow Us</sup></p>
                    <ul>
                        <li><a href="/wiki" target="_blank">Wiki</a></li>
                        <li><a href="https://github.com/openEHR" target="_blank">GitHub</a></li>
                        <li><a href="https://www.youtube.com/openEHR" target="_blank">YouTube</a></li>
                    </ul>
                </div>
            </div>
            <br class="clear">
        </div>
    </div>
    <div id = "BottomPanelContainer">
        <div id="BottomPanel">
            <div id = "WebLinks">
                <span><a href ="https://www.openehr.org/using_the_site/terms_of_use">Terms of use</a> | <a href ="https://www.openehr.org/using_the_site/privacy_policy">Privacy policy</a> | <a href ="https://www.openehr.org/using_the_site/feedback">Feedback</a> | <a href ="/using_the_site/site_map">Site map</a> | <a href="mailto:webmaster@openehr.org">Webmaster</a></span><br/>
                <span>Copyright &copy; <?php echo date("Y");?> openEHR Foundation. All rights reserved</span>
            </div>
            <div id = "Acknowledgements">
                <span>Acknowledgements: <a href="https://www.atlassian.com/" target="_blank">Atlassian</a> (Jira, Confluence) | <a href="https://www.nomagic.com/" target="_blank">NoMagic</a> (MagicDraw UML) | <a href="http://asciidoctor.org/" target="_blank">AsciiDoctor</a> (publishing) | <a href="https://github.com/" target="_blank">GitHub</a> (DVCS) | <a href="https://en.wikipedia.org/wiki/LAMP_%28software_bundle%29" target="_blank">LAMP</a> dev community</span>
            </div>
            <br class="clear">
        </div>
    </div>
