<div id="BottomPanelContainer">
    <div id="BottomPanel">
        <div id="WebLinks">
            <a href="https://www.openehr.org/using_the_site/terms_of_use">Terms of use</a> |
            <a href="https://www.openehr.org/using_the_site/privacy_policy">Privacy policy</a> |
            <a href="https://www.openehr.org/using_the_site/publishing_content">Publishing Content</a> |
            <a href="https://www.openehr.org/using_the_site/localisation">Localisation</a> |
            <a href="https://www.openehr.org/using_the_site/feedback">Feedback</a> |
            <a href="mailto:webmaster@openehr.org">Webmaster</a>
            <br>
            <span>Copyright © <?php echo date("Y");?> openEHR Foundation. All rights reserved</span>
            <br>
            <img src="https://www.openehr.org/static/img/logo_bottom.png" width="100" style="padding:10px 0;"><br>
        </div>
        <div id="Acknowledgements">
            <div class="text-right">
                <a href="https://discourse.openehr.org" class="fa fa-comment" title="Discourse Forums"></a>
                <a href="https://www.openehr.org/wiki" target="_blank" class="fa fa-wikipedia-w" title="Wiki"></a>
                <a href="https://github.com/openEHR" target="_blank" class="fa fa-github" title="Github"></a>
                <a href="https://www.openehr.org/digital_media/blogs" class="fa fa-newspaper-o" title="Blogs"></a>
                <a href="https://www.youtube.com/openEHR" target="_blank" class="fa fa-youtube" title="YouTube"></a>
                <a href="https://twitter.com/#!/openehr" target="_blank" class="fa fa-twitter" title="Twitter"></a>
                <a href="https://www.facebook.com/groups/openehr/" target="_blank" class="fa fa-facebook" title="Facebook"></a>
                <br>
                <span>Acknowledgements:
                    <a href="https://www.atlassian.com/" target="_blank">Atlassian</a> (Jira, Confluence) |
                    <a href="https://www.nomagic.com/" target="_blank">NoMagic</a> (MagicDraw UML) <br>
                    <a href="https://asciidoctor.org/" target="_blank">AsciiDoctor</a> (publishing) |
                    <a href="https://github.com/" target="_blank">GitHub</a> (DVCS) |
                    <a href="https://en.wikipedia.org/wiki/LAMP_%28software_bundle%29" target="_blank">LAMP</a> dev community
                </span>
            </div>
        </div>
        <br class="clear">
    </div>
</div>
