<!DOCTYPE HTML>

<html lang="en">

<head>

	<title>openEHR - <?=$title?></title>
	<meta charset="utf-8">
	<meta name="description" content="openEHR provides open source specifications and reference implementations of future proof EHR systems">
	<meta name="keywords" content="archetypes, openEHR, EHR, electronic health record, electronic medical record, ADL, reference model, clinical models, healthcare, health informatics, medical informatics, EHR standards, ISO 18308, CEN 13606, health care software, open source software, knowledge modelling, patient-centric">
	<meta name="author" content="openEHR Foundation">
	<meta name="designer" content="Adriana Danilakova">
	<meta name="rating" content="General">
	<meta name="robots" content="All">
	<meta name="revisit-after" content="5 days">

	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<link rel="stylesheet" href="/styles/basic.css"  type="text/css">
	<link rel="stylesheet" href="/styles/pages.css"  type="text/css">

	<link rel="shortcut icon" href="/favicon.ico">
    <link rel="icon" sizes="16x16 32x32" href="/favicon.ico">

    <link rel="home" href="/">

	<meta name="google-site-verification" content="zfPZfHQ-5oXYT119aAi7HdZELv8ubHPCxvIFANVPzcU" />

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

	<script src="/functions/menu_dropdown.js"></script>
	<script src="/functions/paragraph_dropdown.js"></script>
</head>

<body>

<div id="MainFrame">
    <?=$this->fetch('layout/top_panel.phtml', $data)?>
    <?=$this->fetch('layout/top_menu.phtml', $data)?>
	<div id="MainAreaContainer">
        <div id="MainArea">
            <div id="SideMenu">
                <?=$this->fetch('layout/side_menu.phtml', $data)?>
            </div>
            <div id="Content">
                <?=$content?>
            </div>
        </div>
        <br class="clear">
    </div>
    <?=$this->fetch('layout/footer.phtml', $data)?>
</div>
<script type="text/javascript">
    var dropdown=new MENU.dropdown.init("dropdown", {id:'menu', active:'menuhover'});
</script>
</body>
</html>
