<!doctype html>
<html lang="en">
<head>
	<title>openEHR - <?=$title??'specifications'?></title>
    <meta charset="utf-8">
	<meta name="description" content="<?=$description??'openEHR provides open source specifications and reference implementations of future proof EHR systems'?>">
	<meta name="author" content="openEHR Foundation - Specification Program">
	<meta name="designer" content="Sebastian Iancu">
	<meta name="rating" content="General">
	<meta name="robots" content="index, follow">
	<meta name="revisit-after" content="5 days">
	<meta name="google-site-verification" content="zfPZfHQ-5oXYT119aAi7HdZELv8ubHPCxvIFANVPzcU"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="/fontawesome/css/all.min.css">
    <link rel="stylesheet" href="/styles/specifications.css" type="text/css">

	<link rel="shortcut icon" href="/favicon.ico">
    <link rel="icon" sizes="16x16 32x32" href="/favicon.ico">

    <link rel="home" href="/">
</head>
<body>
<header class="container-fluid d-flex flex-row justify-content-start align-items-center pt-2">
    <a href="/"><img src="/images/Logo.png" alt="openEHR Specifications" class="logo img-fluid"></a>
    <h6 class="motto d-none d-sm-flex ml-3">Open industry specifications, models <br/>and software for e-health</h6>
</header>
<?=$this->fetch('layout/navbar.phtml', $data)?>
<main id="page_<?=$page?>" class="container pt-2 pb-5">
    <?=$content?>
</main>
<footer class="container-fluid py-2">
    <div class="row">
        <div class="col-sm-auto order-sm-last">
            <nav class="nav">
                <a href="https://discourse.openehr.org" class="fab fa-discourse fa-lg mt-2 mr-2" title="Discourse Forums"></a>
                <a href="https://www.openehr.org/wiki" target="_blank" class="fab fa-wikipedia-w fa-lg m-2" title="Wiki"></a>
                <a href="https://github.com/openEHR" target="_blank" class="fab fa-github-square fa-lg m-2" title="Github"></a>
                <a href="https://www.openehr.org/digital_media/blogs" class="far fa-newspaper fa-lg m-2" title="Blogs"></a>
                <a href="https://www.youtube.com/openEHR" target="_blank" class="fab fa-youtube fa-lg m-2" title="YouTube"></a>
                <a href="https://www.linkedin.com/groups/144276" target="_blank" class="fab fa-linkedin fa-lg m-2" title="LinkedIn"></a>
                <a href="https://twitter.com/#!/openehr" target="_blank" class="fab fa-twitter-square fa-lg m-2" title="Twitter"></a>
                <a href="https://www.facebook.com/groups/openehr/" target="_blank" class="fab fa-facebook-square fa-lg m-2" title="Facebook"></a>
            </nav>
        </div>
        <div class="col-sm order-sm-first">
            <nav class="nav">
                <a href="https://www.openehr.org/using_the_site/terms_of_use" class="mr-1">Terms of use</a> |
                <a href="https://www.openehr.org/using_the_site/privacy_policy" class="mx-1">Privacy policy</a> |
                <a href="mailto:webmaster@openehr.org" class="mx-1">Webmaster</a>
            </nav>
        </div>
    </div>
    <div class="row">
        <div class="col-md">
            <img src="https://www.openehr.org/static/img/logo_inverse.svg" class="logo img-fluid">
            <br/>
            <span>Copyright © <?php echo date("Y");?> openEHR Foundation. All rights reserved</span>
        </div>
        <div class="col-md d-none d-md-block">
            <nav class="nav justify-content-end">
                Acknowledgements:
                <span class="mx-1"><a href="https://www.atlassian.com/" target="_blank">Atlassian</a> (Jira, Confluence)</span> |
                <span class="mx-1"><a href="https://www.nomagic.com/" target="_blank">NoMagic</a> (MagicDraw UML)</span> |
                <span class="mx-1"><a href="https://asciidoctor.org/" target="_blank">AsciiDoctor</a> (publishing)</span> |
                <span class="mx-1"><a href="https://github.com/" target="_blank">GitHub</a> (DVCS)</span> |
                <span class="mx-1"><a href="https://en.wikipedia.org/wiki/LAMP_%28software_bundle%29" target="_blank">LAMP</a> dev community</span>
            </nav>
        </div>
    </div>
</footer>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
</body>
</html>
