<ul>
    <li><a href="/" <?php if($page === 'working_baseline'){?> class="active"<?php }?>>Working Baseline</a></li>
    <li><a href="/latest_releases" <?php if($page === 'latest_releases'){?> class="active"<?php }?>>Latest Releases</a></li>
    <li><a href="/historical_releases" <?php if($page === 'historical_releases'){?> class="active"<?php }?>>Historical Releases</a></li>
    <li><a href="/classes" <?php if($page === 'class_index'){?> class="active"<?php }?>>Class Index</a></li>
    <br/>
    <li><a href="https://openehr.atlassian.net/secure/Dashboard.jspa?selectPageId=10190" target="_blank">Issue Trackers</a></li>
    <li><a href="https://discourse.openehr.org/c/specifications" target="_blank">Discourse Forum</a></li>
    <li><a href="/wiki/display/spec/Specifications+Home" target="_blank">Wiki</a></li>
    <br/>
    <li><a href="https://www.openehr.org/programs/specification/governance" target="_blank">Governance</a></li>
    <li><a href="https://www.openehr.org/governance/intellectual_property" target="_blank">IP and Licensing</a></li>
</ul>
