	<div id="TopPanelContainer">
		<div id="TopPanel">
			<div id="Logo">
				<a href="/"></a>
			</div>
			<div id="Motto">
				Open industry specifications, models and software for e-health
			</div>
			<div id="Utilities">
				<a href="https://www.openehr.org">openEHR Home</a> | <a href="/wiki" target="_blank">Wiki</a> | <a href="https://openehr.atlassian.net/secure/BrowseProjects.jspa?selectedCategory=all&selectedProjectType=all" target="_blank">Jira</a> | <a href="https://www.openehr.org/ckm">CKM</a>
				<div id="Search">
					<script>
					  (function() {
						var cx = '013258992131926468583:q3vo4hyneyu';
						var gcse = document.createElement('script');
						gcse.type = 'text/javascript';
						gcse.async = true;
						gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
						var s = document.getElementsByTagName('script')[0];
						s.parentNode.insertBefore(gcse, s);
					  })();
					</script>
					<gcse:search></gcse:search>
				</div>
			</div>
		</div>
	</div>
	<
